title: "Open Data Day SEGES 2022"
description: Conheça os dados abertos da Secretaria de Gestão
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table"]
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-leap-day
show_downloads: false
github:
  link_url: https://tube.nocturlab.fr/videos/watch/59903907-8a90-45dc-904d-3e651a2ebe09
  link_name: Assistir
