title: "Open Data Day SEGES 2024"
description: Conheça os dados abertos da Secretaria de Gestão e Inovação
markdown: GFM
commonmark:
  extensions: ["table", "iframe"]
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
theme: jekyll-theme-leap-day
show_downloads: false
video:
  link_url: https://fediverse.tv/w/mQg4kByFYqsvWxH1TRZvk1
  link_name: ▶️ Assistir ao streaming
lab:
  link_url: notebooks
  link_name: 🧪 Laboratório
