title: "Open Data Day SEGES 2024"
description: Conheça os dados abertos da Secretaria de Gestão e Inovação
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table"]
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
theme: jekyll-theme-leap-day
show_downloads: false
github:
  link_url: assets/notebooks
  link_name: Laboratório
